language: python

python:
  - 2.7

sudo: required

services:
  - docker

env:
  global:
    - REPO=driesschulten/aws-node-circleci
    - secure: Y1uxiaCfJRg6mtaZO+NXTRoFP9N//5vCJY1XzzIBv6cZio6i7V8U4NM04dnmL2amsm7RCJw9tcBKZNJ5uLp4bO7uh5BYkhR/sQnsiAXynthq9r3XEE+Qs0iDqx8VYzZIj65cftUfRI2Du8u/xG78Q/YPAcU6khq1saUdn+Q1cAo3yM5Tn2xDiKAmN3faCL0gjhlVN3TATfymw5Rvhj8wNmUTzFFFEzoOUnVzuzAAd4jRhnXa2Ii1z8ZjmnrKpgtTlaASIPSBHXWXKKzsMmISnq1f03cckql+WiT2pn90/NuMgYMBP74tRcLMalFwQhXSmx/PiwCi/i+R2k1oR3v8bem2JEni8uhYy87Ne8jz2cGGD8zHxnMnpr//oVwiMH/yatgDz5AE/XzhP2RAE7j4VMjEc/niEsPLx/qxpbSNW4iowzfhXK04grbty5/rJ6bn/SVB24uA7wHA5nEykr+jMXMC6ExatBuXcAbbi5QlWc/A28ODXb4vb6ZgFF8ELdrGgZxQ09YEzvRHeHh21bOE9UsE1YdMhq84ta58ZRv2J7SnnsWebAmDvUKjBVkdvzQ9TjTAuLHZPtxYoI9Hp5+eGSWzLQ/mAMdsIgTHfrdwrsAKiZltgkFRsBFyLgD6RaT2C9JxcKUgwkxMl3dBDxdIMA15CZtd2lYpR323JT9OijM=
    - secure: KNWFPgZf4xeXotW6XTEvdp0RulYRSNEnIch5WWQqq1AB+xjfZBlaXDKDhHE9kg5n9wdS2BTBgALo3UfeWB7TJAmQuF93Zr+qS3BzyalkFZVvsopUs2pWRZGk6rk7qLcdXhCZIEAL0NXsm1Xq24C/lWoHTi8uPx9yf+sys2dLGbW4Bghbkf9XRI1SzVQmv+ZVhBc0NU5yhGDfFw/+TUEjZoqrykr9qEqP8O+CaqHPpyKpE/77RFdywnGiTtZxDyhHWgQfxQbpAR/6AkXogkLSu9ZPFqz0Qan/QvHnPcZUq9LBxKmtIUKlnR2K+8f8EeMi8yp/rzolatAI5k6BvFIu1FPFZF1LECQ6IA5/x8g+GfQIRln/6xGo9U6kAb21p2R9ta4JfEdsybIiOFPjKrNIxu+/Ie+Pd1kFUScoysAUbDdFbF3n1qU2JEF2gqUPPdXLnBeeKFnLyX0ioJ48xDt8LTl9AVZTrg3vhMqCkIOh2qUALKXIvUoVutmQ2UPA03DXDCcxbgfWJNJ+JNBlRjSB1IzZ8ChpDs8sfGOuNf9JSl21VmK9DQ8I2FQbPcwVQKM/1xbgziL2My6UKluD2WjJRtFuhEQxf7S3z8H24xySosKqYcGR9Lfhml2FLWYKTSoGoAj61/jDLMihE4dNDSAJvlgl331nPOjjXBuyWGhVJTc=

install:
  - docker build -t $REPO .

script: echo 'no tests!'

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag $REPO $REPO:latest
  - if [[ $TRAVIS_TAG ]]; then docker tag $REPO $REPO:$TRAVIS_TAG; fi
  - docker push $REPO
